//! Minimal editing of a QMK `keymap.c` generated by Oryx: locate each layer's
//! `LAYOUT_voyager( … )` block and replace a keycode by position.
//!
//! The macro arguments are in the keyboard's `LAYOUT` order, which is the same
//! index keyjitsu stores as `GeoKey::led` - so a per-key RGB index, a `ledmap`
//! entry and a `LAYOUT_*` argument all share one position.

use anyhow::{anyhow, bail, Result};

/// One remap to apply: on layer `layer`, set `LAYOUT` position `position` to
/// the QMK `keycode` string.
#[derive(Debug, Clone)]
pub struct Edit {
    pub layer: u8,
    pub position: usize,
    pub keycode: String,
}

/// One tap-dance to generate: on layer `layer`, position `position`, the key
/// gets `TD(DANCE_KJ_i)` implementing up to four actions.
#[derive(Debug, Clone, Default)]
pub struct DanceSpec {
    pub layer: u8,
    pub position: usize,
    /// Single tap keycode.
    pub tap: Option<String>,
    /// Press-and-hold: `MO(n)` or a keycode (modifier etc.).
    pub hold: Option<String>,
    /// Double tap keycode.
    pub double_tap: Option<String>,
    /// Tap-then-hold (QMK DOUBLE_HOLD): `MO(n)` or a keycode.
    pub tap_hold: Option<String>,
}

/// The layer-switch keycode families - these drive layers and are NOT
/// `register_code16`-able. Kept in one place so [`action_stmts`] and the
/// fast-double-tap gate can't disagree about what counts as a layer op.
const LAYER_SWITCH_PREFIXES: &[&str] = &["MO(", "TO(", "TG(", "TT(", "OSL(", "DF(", "LT("];

/// Whether `code` is one of the [`LAYER_SWITCH_PREFIXES`] families.
fn is_layer_switch(code: &str) -> bool {
    LAYER_SWITCH_PREFIXES.iter().any(|p| code.starts_with(p))
}

/// The (press, release) C statements for an action keycode inside a tap dance.
/// Layer-switch families become real layer ops (a raw `register_code16(MO(1))`
/// would NOT switch layers); everything else is a plain keycode.
fn validate_dance_action(code: &str) -> Result<()> {
    for step in code.split('\n').map(str::trim).filter(|step| !step.is_empty()) {
        let nested_tap_hold = step.starts_with("TT(")
            || step.starts_with("LT(")
            || step.starts_with("MT(")
            || [
                "LCTL_T(", "RCTL_T(", "LSFT_T(", "RSFT_T(", "LALT_T(", "RALT_T(",
                "LGUI_T(", "RGUI_T(", "HYPR_T(", "MEH_T(",
            ]
            .iter()
            .any(|prefix| step.starts_with(prefix));
        if nested_tap_hold {
            bail!(
                "{step} cannot be nested inside a generated tap dance; use the separate Tap/Hold slots or a plain key assignment"
            );
        }
    }
    Ok(())
}

fn action_stmts(code: &str) -> (String, String) {
    // A multi-step macro (see MacroSpec): tap every step fully, in order, the
    // moment the dance resolves - nothing is left held, so there is no
    // release-side statement.
    if code.contains('\n') {
        let mut taps = String::new();
        for step in code.split('\n').map(str::trim).filter(|step| !step.is_empty()) {
            let (press, release) = action_stmts(step);
            taps.push_str(&press);
            if !press.is_empty() && !release.is_empty() {
                taps.push(' ');
            }
            taps.push_str(&release);
            taps.push(' ');
        }
        return (taps.trim_end().to_string(), String::new());
    }
    // Momentary-style: on at press, off at release.
    if let Some(n) = code.strip_prefix("MO(").and_then(|r| r.strip_suffix(')')) {
        return (format!("layer_on({});", n.trim()), format!("layer_off({});", n.trim()));
    }
    // Preserve QMK one-shot semantics instead of treating OSL as a momentary
    // layer. When one-shot keys are disabled, QMK itself falls back to MO.
    if let Some(n) = code.strip_prefix("OSL(").and_then(|r| r.strip_suffix(')')) {
        let n = n.trim();
        return (
            format!("if (is_oneshot_enabled()) {{ set_oneshot_layer({n}, ONESHOT_START); }} else {{ layer_on({n}); }}"),
            format!("if (is_oneshot_enabled()) {{ clear_oneshot_layer_state(ONESHOT_PRESSED); }} else {{ layer_off({n}); }}"),
        );
    }
    if let Some(mods) = code.strip_prefix("OSM(").and_then(|r| r.strip_suffix(')')) {
        let mods = mods.trim();
        return (
            format!("if (is_oneshot_enabled()) {{ set_oneshot_mods({mods}); }} else {{ register_mods({mods}); }}"),
            format!("if (!is_oneshot_enabled()) {{ unregister_mods({mods}); }}"),
        );
    }
    // A layer-tap held inside a dance = hold half = momentary that layer.
    if let Some(rest) = code.strip_prefix("LT(").and_then(|r| r.strip_suffix(')')) {
        if let Some(n) = rest.split(',').next() {
            return (format!("layer_on({});", n.trim()), format!("layer_off({});", n.trim()));
        }
    }
    if let Some(n) = code.strip_prefix("TO(").and_then(|r| r.strip_suffix(')')) {
        return (format!("layer_move({});", n.trim()), String::new());
    }
    // Toggle-style: no release action.
    for pfx in ["TG(", "TT("] {
        if let Some(n) = code.strip_prefix(pfx).and_then(|r| r.strip_suffix(')')) {
            return (format!("layer_invert({});", n.trim()), String::new());
        }
    }
    if let Some(n) = code.strip_prefix("DF(").and_then(|r| r.strip_suffix(')')) {
        // default_layer_set() takes a layer-state bitmask, not a layer index.
        return (format!("default_layer_set(1UL << {});", n.trim()), String::new());
    }
    (format!("register_code16({code});"), format!("unregister_code16({code});"))
}

/// Generate `TD(DANCE_KJ_i)` keycodes plus the Oryx-style tap-dance plumbing
/// (enum entries, per-dance state + finished/reset functions, action array).
/// Reuses infrastructure already present in an Oryx keymap.c; creates it when
/// the source has no dances yet.
pub fn apply_dances(source: &str, dances: &[DanceSpec]) -> Result<String> {
    if dances.is_empty() {
        return Ok(source.to_string());
    }
    for (index, dance) in dances.iter().enumerate() {
        for (slot, code) in [
            ("tap", &dance.tap),
            ("hold", &dance.hold),
            ("double tap", &dance.double_tap),
            ("tap-hold", &dance.tap_hold),
        ] {
            if let Some(code) = code {
                validate_dance_action(code).map_err(|e| {
                    anyhow!("tap dance {} {slot}: {e}", index + 1)
                })?;
            }
        }
    }
    let mut out = source.to_string();

    // 1. Swap the key slots to TD(DANCE_KJ_i).
    for (i, d) in dances.iter().enumerate() {
        out = apply_one(
            &out,
            &Edit { layer: d.layer, position: d.position, keycode: format!("TD(DANCE_KJ_{i})") },
        )?;
    }

    // 2. Dance names into the `tap_dance_codes` enum (create it if missing).
    let names: String = (0..dances.len()).map(|i| format!("  DANCE_KJ_{i},
")).collect();
    if let Some(e) = out.find("enum tap_dance_codes") {
        let close = out[e..].find("};").map(|r| e + r).ok_or_else(|| anyhow!("unterminated tap_dance_codes enum"))?;
        out.insert_str(close, &names);
    } else {
        let km = out
            .find("const uint16_t PROGMEM keymaps")
            .ok_or_else(|| anyhow!("no keymaps[] in keymap.c"))?;
        out.insert_str(km, &format!("enum tap_dance_codes {{
{names}}};

"));
    }

    // 3. Shared step machinery (only when the source has none).
    if !out.contains("uint8_t dance_step(") {
        out.push_str(
            "
typedef struct {
    bool is_press_action;
    uint8_t step;
} tap;

enum {
    SINGLE_TAP = 1,
    SINGLE_HOLD,
    DOUBLE_TAP,
    DOUBLE_HOLD,
    DOUBLE_SINGLE_TAP,
    MORE_TAPS
};

uint8_t dance_step(tap_dance_state_t *state);

uint8_t dance_step(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (state->interrupted || !state->pressed) return SINGLE_TAP;
        else return SINGLE_HOLD;
    } else if (state->count == 2) {
        if (state->interrupted) return DOUBLE_SINGLE_TAP;
        else if (state->pressed) return DOUBLE_HOLD;
        else return DOUBLE_TAP;
    }
    return MORE_TAPS;
}
",
        );
    }

    // 4. Per-dance state + finished/reset functions.
    let mut fns = String::new();
    let mut entries = String::new();
    for (i, d) in dances.iter().enumerate() {
        let mut fin = String::new();
        let mut rst = String::new();
        let mut arm = |step: &str, code: &Option<String>, double_single: bool| {
            if let Some(c) = code {
                let (on, off) = action_stmts(c);
                fin.push_str(&format!("        case {step}: {on} break;
"));
                if !off.is_empty() {
                    rst.push_str(&format!("        case {step}: {off} break;
"));
                }
                // The fast-double-tap arm only makes sense for plain keycodes,
                // never a layer-switch family (they aren't register_code16-able).
                if double_single && !is_layer_switch(c) && !c.contains('\n') {
                    fin.push_str(&format!("        case DOUBLE_SINGLE_TAP: tap_code16({c}); register_code16({c}); break;
"));
                    rst.push_str(&format!("        case DOUBLE_SINGLE_TAP: unregister_code16({c}); break;
"));
                }
            }
        };
        arm("SINGLE_TAP", &d.tap, true);
        arm("SINGLE_HOLD", &d.hold, false);
        arm("DOUBLE_TAP", &d.double_tap, false);
        arm("DOUBLE_HOLD", &d.tap_hold, false);
        fns.push_str(&format!(
            "
static tap dance_state_kj_{i};

void dance_kj_{i}_finished(tap_dance_state_t *state, void *user_data);
void dance_kj_{i}_reset(tap_dance_state_t *state, void *user_data);

void dance_kj_{i}_finished(tap_dance_state_t *state, void *user_data) {{
    dance_state_kj_{i}.step = dance_step(state);
    switch (dance_state_kj_{i}.step) {{
{fin}    }}
}}

void dance_kj_{i}_reset(tap_dance_state_t *state, void *user_data) {{
    wait_ms(10);
    switch (dance_state_kj_{i}.step) {{
{rst}    }}
    dance_state_kj_{i}.step = 0;
}}
"
        ));
        entries.push_str(&format!(
            "        [DANCE_KJ_{i}] = ACTION_TAP_DANCE_FN_ADVANCED(NULL, dance_kj_{i}_finished, dance_kj_{i}_reset),
"
        ));
    }

    // 5. Register in tap_dance_actions[] (extend the existing array, or append
    //    a new one). The functions must be defined before the array.
    if let Some(arr) = out.find("tap_dance_actions[] = {") {
        // Back up to the start of the declaration line.
        let decl = out[..arr].rfind('\n').map(|n| n + 1).unwrap_or(0);
        out.insert_str(decl, &format!("{fns}
"));
        let arr = out.find("tap_dance_actions[] = {").ok_or_else(|| anyhow!("tap_dance_actions disappeared while patching"))?;
        let close = out[arr..].find("};").map(|r| arr + r).ok_or_else(|| anyhow!("unterminated tap_dance_actions"))?;
        out.insert_str(close, &entries);
    } else {
        out.push_str(&fns);
        out.push_str(&format!("
tap_dance_action_t tap_dance_actions[] = {{
{entries}}};
"));
    }

    // 6. Give each generated dance a comfortable tapping term (default 200ms)
    //    so double-tap-hold is actually reachable. Oryx keys can carry a tiny
    //    per-key term (e.g. 50ms) that makes the gesture near-impossible.
    out = apply_dance_tapping_term(&out, dances.len());

    Ok(out)
}

/// Comfortable per-key tapping term for a generated dance, in ms.
const DANCE_TAPPING_TERM: u32 = 200;

/// Add a `case TD(DANCE_KJ_i): return DANCE_TAPPING_TERM;` for each generated dance to the
/// `get_tapping_term` switch (creating the function - and its enabling define
/// isn't needed here, Oryx sources with dances already set TAPPING_TERM_PER_KEY;
/// when absent we still emit the function, harmless without the flag).
fn apply_dance_tapping_term(source: &str, n: usize) -> String {
    if n == 0 {
        return source.to_string();
    }
    let cases: String = (0..n)
        .map(|i| format!("        case TD(DANCE_KJ_{i}): return {DANCE_TAPPING_TERM};\n"))
        .collect();
    let mut out = source.to_string();
    if let Some(f) = out.find("get_tapping_term(") {
        // Insert our cases right before the switch's `default:` (or, failing
        // that, before the switch's closing brace).
        if let Some(drel) = out[f..].find("default:") {
            let at = f + drel;
            let line = out[..at].rfind('\n').map(|n| n + 1).unwrap_or(at);
            out.insert_str(line, &cases);
        }
        out
    } else {
        // No get_tapping_term yet - append one. Needs TAPPING_TERM_PER_KEY in
        // config.h to take effect; localbuild ensures that separately.
        out.push_str(&format!(
            "\nuint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {{\n    switch (keycode) {{\n{cases}        default: return TAPPING_TERM;\n    }}\n}}\n"
        ));
        out
    }
}

/// One generated macro: a custom keycode that, on press, executes every step
/// in `steps` as a complete action (press+release where applicable), in order.
/// Used for a key whose Tap (or Hold/Double-tap/Tap-hold) slot has more than
/// one step but ISN'T going through the tap-dance machinery - i.e. a plain
/// `LAYOUT` position, not a `TD()`. Unlike a dance, there is no tap/hold
/// ambiguity to resolve, so this fires the instant the key is pressed.
#[derive(Debug, Clone)]
pub struct MacroSpec {
    pub id: usize,
    pub steps: Vec<String>,
}

/// Generate `MACRO_KJ_{id}` custom keycodes plus a `process_record_user` case
/// per macro that taps its steps in order. Creates the custom-keycode enum
/// and `process_record_user` fresh each build (the Oryx source keyjitsu
/// starts from never has either), extending an existing
/// `process_record_user` if the source unexpectedly already has one rather
/// than silently dropping it.
pub fn apply_macros(source: &str, macros: &[MacroSpec]) -> Result<String> {
    if macros.is_empty() {
        return Ok(source.to_string());
    }
    let mut out = source.to_string();

    // 1. Allocate custom keycodes without colliding with custom keycodes that
    // Oryx may already have emitted. If an enum already owns SAFE_RANGE, append
    // our names to that enum so C continues numbering after its last entry.
    let plain_names: String = macros
        .iter()
        .map(|m| format!("    MACRO_KJ_{},\n", m.id))
        .collect();
    if let Some(safe) = out.find("SAFE_RANGE") {
        let open = out[..safe]
            .rfind('{')
            .ok_or_else(|| anyhow!("SAFE_RANGE is not inside an enum-like block"))?;
        let close = matching_brace(&out, open)?;
        let body = &out[open + 1..close];
        let separator = if body.trim_end().ends_with(',') { "" } else { "," };
        out.insert_str(close, &format!("{separator}\n{plain_names}"));
    } else {
        let mut names = String::new();
        for (i, m) in macros.iter().enumerate() {
            if i == 0 {
                names.push_str(&format!("    MACRO_KJ_{} = SAFE_RANGE,\n", m.id));
            } else {
                names.push_str(&format!("    MACRO_KJ_{},\n", m.id));
            }
        }
        let km = out
            .find("const uint16_t PROGMEM keymaps")
            .ok_or_else(|| anyhow!("no keymaps[] in keymap.c"))?;
        out.insert_str(km, &format!("enum keyjitsu_macro_keycodes {{\n{names}}};\n\n"));
    }

    // 2. One `case MACRO_KJ_i:` per macro, executing each full action in
    // order. Layer-family keycodes need real QMK layer operations rather than
    // tap_code16, which does not activate layer keycodes.
    let mut cases = String::new();
    for m in macros {
        let mut taps = String::new();
        for step in &m.steps {
            let (press, release) = action_stmts(step.trim());
            taps.push_str(&press);
            if !press.is_empty() && !release.is_empty() {
                taps.push(' ');
            }
            taps.push_str(&release);
            taps.push(' ');
        }
        cases.push_str(&format!(
            "        case MACRO_KJ_{}:\n            if (record->event.pressed) {{ {} }}\n            return false;\n",
            m.id,
            taps.trim_end()
        ));
    }
    if let Some(f) = out.find("bool process_record_user(uint16_t keycode, keyrecord_t *record) {") {
        let body_start = out[f..].find('{').map(|r| f + r + 1).ok_or_else(|| anyhow!("malformed process_record_user"))?;
        out.insert_str(body_start, &format!("\n    switch (keycode) {{\n{cases}        default: break;\n    }}\n"));
    } else {
        out.push_str(&format!(
            "\nbool process_record_user(uint16_t keycode, keyrecord_t *record) {{\n    switch (keycode) {{\n{cases}    }}\n    return true;\n}}\n"
        ));
    }
    Ok(out)
}

/// Apply all `edits` to `source` (the text of a `keymap.c`), returning the new
/// text. Fails if a targeted layer/position can't be found.
pub fn apply_edits(source: &str, edits: &[Edit]) -> Result<String> {
    let mut out = source.to_string();
    for edit in edits {
        out = apply_one(&out, edit)?;
    }
    Ok(out)
}

fn apply_one(source: &str, edit: &Edit) -> Result<String> {
    let (_, inner_start, inner_end) = find_layer_block(source, edit.layer)?;
    let inner = &source[inner_start..inner_end];
    let mut tokens = split_top_level(inner);
    if edit.position >= tokens.len() {
        bail!(
            "layer {} has {} keys but position {} was requested",
            edit.layer,
            tokens.len(),
            edit.position
        );
    }
    // Preserve the original leading/trailing whitespace of the slot so the file
    // stays roughly aligned; just swap the trimmed keycode.
    let slot = &tokens[edit.position];
    let lead: String = slot.chars().take_while(|c| c.is_whitespace()).collect();
    tokens[edit.position] = format!("{lead}{}", edit.keycode);

    let rebuilt = tokens.join(",");
    let mut result = String::with_capacity(source.len());
    result.push_str(&source[..inner_start]);
    result.push_str(&rebuilt);
    result.push_str(&source[inner_end..]);
    Ok(result)
}

/// Append a brand-new layer block `[position] = LAYOUT_*( … )` at the end of
/// the `keymaps[]` array. Sized/named from layer 0; every key is
/// `KC_TRANSPARENT` except the `(position → keycode)` entries in `keys`
/// (positions are LAYOUT-macro indices). Enables authoring layers that don't
/// exist in the Oryx source.
pub fn add_layer(source: &str, position: u8, keys: &[(usize, String)]) -> Result<String> {
    // Refuse to append a layer index that already exists - a second
    // `[position] = LAYOUT(...)` silently overrides the real one in C.
    if find_layer_block(source, position).is_ok() {
        bail!("layer [{position}] already exists in keymap.c");
    }
    // Key count + macro name come from layer 0.
    let (l0_start, s0, e0) = find_layer_block(source, 0)?;
    let count = split_top_level(&source[s0..e0]).len();
    if let Some((pos, _)) = keys.iter().find(|(p, _)| *p >= count) {
        bail!("key position {pos} is out of range for a {count}-key layer");
    }
    // Macro name: the `LAYOUT…` token between `[0]` and its `(`.
    let head = &source[l0_start..s0]; // e.g. "[0] = LAYOUT_voyager("
    let macro_name = head
        .split_whitespace()
        .find_map(|t| t.split('(').next().filter(|w| w.starts_with("LAYOUT")))
        .ok_or_else(|| anyhow!("could not read the LAYOUT macro name"))?
        .to_string();

    let mut tokens = vec!["KC_TRANSPARENT".to_string(); count];
    for (pos, code) in keys {
        if *pos < count {
            tokens[*pos] = code.clone();
        }
    }
    let block = format!("  [{position}] = {macro_name}(\n    {}\n  ),\n", tokens.join(", "));

    // Insert before the keymaps[] array's closing brace.
    let km = source
        .find("PROGMEM keymaps")
        .ok_or_else(|| anyhow!("no keymaps[] in keymap.c"))?;
    let open = km + source[km..].find('{').ok_or_else(|| anyhow!("keymaps[] has no opening brace"))?;
    let close = matching_brace(source, open)?;

    let mut out = String::with_capacity(source.len() + block.len());
    out.push_str(&source[..close]);
    out.push_str(&block);
    out.push_str(&source[close..]);
    Ok(out)
}

/// Index of the `}` matching the `{` at `open`.
fn matching_brace(source: &str, open: usize) -> Result<usize> {
    let bytes = source.as_bytes();
    let mut depth = 0i32;
    for (i, &b) in bytes.iter().enumerate().skip(open) {
        match b {
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return Ok(i);
                }
            }
            _ => {}
        }
    }
    bail!("unbalanced braces in keymap.c")
}

/// Returns `(macro_start, inner_start, inner_end)` byte offsets for the
/// `[layer] = LAYOUT_*( … )` block: inner spans the arguments between the outer
/// parentheses.
fn find_layer_block(source: &str, layer: u8) -> Result<(usize, usize, usize)> {
    let km = source
        .find("PROGMEM keymaps")
        .ok_or_else(|| anyhow!("no keymaps[] in keymap.c"))?;
    let array_open = km
        + source[km..]
            .find('{')
            .ok_or_else(|| anyhow!("keymaps[] has no opening brace"))?;
    let array_close = matching_brace(source, array_open)?;
    let needle = format!("[{layer}]");
    let mut search_from = array_open + 1;

    while search_from < array_close {
        let Some(rel) = source[search_from..array_close].find(&needle) else {
            break;
        };
        let idx = search_from + rel;
        let after_start = idx + needle.len();
        let after = &source[after_start..array_close];
        if let Some(paren_rel) = after.find('(') {
            let between = &after[..paren_rel];
            if between.contains('=') && between.contains("LAYOUT") {
                let open = after_start + paren_rel;
                let inner_start = open + 1;
                let inner_end = matching_paren(source, open)?;
                if inner_end <= array_close {
                    return Ok((idx, inner_start, inner_end));
                }
            }
        }
        search_from = after_start;
    }
    Err(anyhow!("could not find `[{layer}] = LAYOUT…(` in keymap.c"))
}

/// Index of the `)` matching the `(` at `open`.
fn matching_paren(source: &str, open: usize) -> Result<usize> {
    let bytes = source.as_bytes();
    debug_assert_eq!(bytes[open], b'(');
    let mut depth = 0i32;
    for (i, &b) in bytes.iter().enumerate().skip(open) {
        match b {
            b'(' => depth += 1,
            b')' => {
                depth -= 1;
                if depth == 0 {
                    return Ok(i);
                }
            }
            _ => {}
        }
    }
    bail!("unbalanced parentheses in keymap.c")
}

/// Split a `LAYOUT(...)` argument list on commas that are at paren depth 0, so
/// that nested keycodes like `LT(2, KC_SPC)` stay intact.
fn split_top_level(inner: &str) -> Vec<String> {
    let mut tokens = Vec::new();
    let mut depth = 0i32;
    let mut current = String::new();
    for c in inner.chars() {
        match c {
            '(' => {
                depth += 1;
                current.push(c);
            }
            ')' => {
                depth -= 1;
                current.push(c);
            }
            ',' if depth == 0 => {
                tokens.push(std::mem::take(&mut current));
            }
            _ => current.push(c),
        }
    }
    // Trailing content after the last comma (Oryx emits a trailing comma, so
    // this is usually just whitespace - keep it only if it has a token).
    if current.split_whitespace().next().is_some() {
        tokens.push(current);
    }
    tokens
}

/// Number of key slots in a layer (for validation / tests).
#[cfg_attr(not(test), allow(dead_code))]
pub fn layer_key_count(source: &str, layer: u8) -> Result<usize> {
    let (_, s, e) = find_layer_block(source, layer)?;
    Ok(split_top_level(&source[s..e]).len())
}

#[cfg(test)]
mod tests {
    use super::*;

    // A trimmed but structurally faithful slice of an Oryx keymap.c.
    const SAMPLE: &str = r#"
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = LAYOUT_voyager(
    DUAL_FUNC_0,    KC_1,           KC_2,                           KC_6,           KC_MINUS,
    KC_LEFT_ALT,    KC_SPACE,                       KC_BSPC,        TD(DANCE_0)
  ),
  [1] = LAYOUT_voyager(
    KC_TRANSPARENT, LT(2, KC_A),    MT(MOD_LSFT, KC_B),             KC_6,           KC_PLUS,
    KC_TRANSPARENT, KC_TRANSPARENT,                 KC_DELETE,      KC_TRANSPARENT
  ),
};
"#;

    #[test]
    fn macro_generates_enum_and_process_record_user() {
        let edits = [Edit { layer: 0, position: 1, keycode: "MACRO_KJ_0".into() }];
        let patched = apply_edits(SAMPLE, &edits).unwrap();
        let macros = [MacroSpec { id: 0, steps: vec!["LGUI(KC_C)".into(), "KC_BSPC".into()] }];
        let out = apply_macros(&patched, &macros).unwrap();
        // Position 1 points at our custom keycode.
        let layer0 = &out[out.find("[0]").unwrap()..out.find("[1]").unwrap()];
        assert!(layer0.contains("MACRO_KJ_0"));
        // The enum anchors at SAFE_RANGE, and process_record_user executes
        // both complete actions in order on press, then eats the keycode.
        assert!(out.contains("enum keyjitsu_macro_keycodes"));
        assert!(out.contains("MACRO_KJ_0 = SAFE_RANGE"));
        assert!(out.contains("case MACRO_KJ_0:"));
        let case = &out[out.find("case MACRO_KJ_0:").unwrap()..];
        let first = case.find("register_code16(LGUI(KC_C));").unwrap();
        let second = case.find("register_code16(KC_BSPC);").unwrap();
        assert!(first < second, "steps must fire in the order they were staged");
        assert!(case.contains("unregister_code16(LGUI(KC_C));"));
        assert!(case.contains("unregister_code16(KC_BSPC);"));
        assert!(case.contains("return false;"), "the macro keycode itself must not also register");
        // Defined before first use (process_record_user references it).
        assert!(out.find("enum keyjitsu_macro_keycodes").unwrap() < out.find("process_record_user").unwrap());
    }

    #[test]
    fn macro_layer_steps_use_layer_operations() {
        let out = apply_macros(
            SAMPLE,
            &[MacroSpec {
                id: 0,
                steps: vec!["KC_A".into(), "TO(2)".into(), "DF(3)".into()],
            }],
        )
        .unwrap();
        let case = &out[out.find("case MACRO_KJ_0:").unwrap()..];
        assert!(case.contains("register_code16(KC_A); unregister_code16(KC_A);"));
        assert!(case.contains("layer_move(2);"));
        assert!(case.contains("default_layer_set(1UL << 3);"));
        assert!(!case.contains("tap_code16(TO(2))"));
    }

    #[test]
    fn macros_extend_existing_safe_range_enum_without_reusing_its_value() {
        let src = format!(
            "enum custom_keycodes {{\n    EXISTING = SAFE_RANGE,\n    EXISTING_TWO\n}};\n{SAMPLE}\nbool process_record_user(uint16_t keycode, keyrecord_t *record) {{\n    switch (keycode) {{\n        case EXISTING: return false;\n        default: return true;\n    }}\n}}\n"
        );
        let out = apply_macros(
            &src,
            &[MacroSpec { id: 0, steps: vec!["KC_A".into()] }],
        )
        .unwrap();

        assert_eq!(out.matches("SAFE_RANGE").count(), 1);
        assert!(!out.contains("MACRO_KJ_0 = SAFE_RANGE"));
        let existing = out.find("EXISTING_TWO").unwrap();
        let generated = out.find("MACRO_KJ_0").unwrap();
        let keymaps = out.find("PROGMEM keymaps").unwrap();
        assert!(existing < generated && generated < keymaps);
    }

    #[test]
    fn no_macros_leaves_source_untouched() {
        assert_eq!(apply_macros(SAMPLE, &[]).unwrap(), SAMPLE);
    }

    #[test]
    fn dance_case_taps_multi_step_slot_in_order() {
        // A dance's SINGLE_TAP with a two-step macro ("KC_A\nKC_B") should
        // tap both, in order, instead of the plain register/unregister pair
        // a single keycode gets.
        let d = DanceSpec { layer: 0, position: 1, tap: Some("KC_A\nKC_B".into()), ..Default::default() };
        let out = apply_dances(SAMPLE, std::slice::from_ref(&d)).unwrap();
        let fin = &out[out.find("dance_kj_0_finished").unwrap()..];
        assert!(fin.contains(
            "case SINGLE_TAP: register_code16(KC_A); unregister_code16(KC_A); register_code16(KC_B); unregister_code16(KC_B); break;"
        ));
        // No reset-side statement for a multi-step action: each step completed.
        let rst = &out[out.find("dance_kj_0_reset").unwrap()..];
        let rst_body = &rst[..rst.find('}').unwrap_or(rst.len())];
        assert!(!rst_body.contains("unregister_code16(KC_A)"));
    }

    #[test]
    fn counts_top_level_slots_with_nested_commas() {
        // Layer 1 has LT(2, KC_A) and MT(MOD_LSFT, KC_B) - commas inside must
        // not split the slot.
        assert_eq!(layer_key_count(SAMPLE, 1).unwrap(), 9);
        assert_eq!(layer_key_count(SAMPLE, 0).unwrap(), 9);
    }

    #[test]
    fn layer_lookup_ignores_decoy_indices_outside_keymaps_array() {
        let src = format!(
            "const uint16_t ledmap[][2] = {{ [0] = {{ 1, 2 }} }};\n{SAMPLE}"
        );
        let out = apply_edits(
            &src,
            &[Edit {
                layer: 0,
                position: 1,
                keycode: "KC_ESC".into(),
            }],
        )
        .unwrap();

        let layer0 = &out[out.find("[0] = LAYOUT_voyager").unwrap()..out.find("[1] = LAYOUT_voyager").unwrap()];
        assert!(layer0.contains("KC_ESC"));
        assert!(out.contains("ledmap[][2] = { [0] = { 1, 2 } }"));
    }

    #[test]
    fn replaces_a_keycode_by_position() {
        let edits = [Edit { layer: 0, position: 1, keycode: "KC_ESC".into() }];
        let out = apply_edits(SAMPLE, &edits).unwrap();
        // Position 1 was KC_1 → KC_ESC; KC_2 (pos 2) untouched.
        let layer0 = &out[out.find("[0]").unwrap()..out.find("[1]").unwrap()];
        assert!(layer0.contains("KC_ESC"));
        assert!(!layer0.contains("KC_1,"));
        assert!(layer0.contains("KC_2"));
    }

    #[test]
    fn replace_survives_reparse() {
        let edits = [Edit { layer: 1, position: 0, keycode: "LT(3, KC_TAB)".into() }];
        let out = apply_edits(SAMPLE, &edits).unwrap();
        // Still 9 slots after inserting a keycode that itself contains a comma.
        assert_eq!(layer_key_count(&out, 1).unwrap(), 9);
        assert!(out.contains("LT(3, KC_TAB)"));
    }

    #[test]
    fn add_layer_appends_block() {
        let out = add_layer(SAMPLE, 2, &[(1, "KC_7".into()), (3, "MO(1)".into())]).unwrap();
        // A [2] block now exists, sized like the others (9 slots in SAMPLE).
        assert_eq!(layer_key_count(&out, 2).unwrap(), 9);
        let l2 = &out[out.find("[2]").unwrap()..];
        assert!(l2.contains("LAYOUT_voyager("));
        assert!(l2.contains("KC_7"));
        assert!(l2.contains("MO(1)"));
        // Untouched positions are transparent.
        assert!(l2.matches("KC_TRANSPARENT").count() >= 7);
        // The array still closes cleanly (parse layer 0 still works).
        assert_eq!(layer_key_count(&out, 0).unwrap(), 9);
    }

    #[test]
    fn out_of_range_position_errors() {
        let edits = [Edit { layer: 0, position: 99, keycode: "KC_A".into() }];
        assert!(apply_edits(SAMPLE, &edits).is_err());
    }

    #[test]
    fn dance_on_fresh_source_creates_everything() {
        let d = DanceSpec {
            layer: 0,
            position: 1,
            tap: Some("KC_1".into()),
            hold: Some("MO(2)".into()),
            double_tap: Some("KC_F1".into()),
            tap_hold: None,
        };
        let out = apply_dances(SAMPLE, &[d]).unwrap();
        // Slot swapped, enum created before keymaps, infra + actions appended.
        assert!(out.contains("TD(DANCE_KJ_0)"));
        assert!(out.find("enum tap_dance_codes").unwrap() < out.find("PROGMEM keymaps").unwrap());
        assert_eq!(out.matches("uint8_t dance_step(tap_dance_state_t *state) {").count(), 1);
        assert!(out.contains("case SINGLE_TAP: register_code16(KC_1); break;"));
        assert!(out.contains("case SINGLE_HOLD: layer_on(2); break;"));
        assert!(out.contains("case SINGLE_HOLD: layer_off(2); break;"));
        assert!(out.contains("case DOUBLE_TAP: register_code16(KC_F1); break;"));
        assert!(out.contains("[DANCE_KJ_0] = ACTION_TAP_DANCE_FN_ADVANCED(NULL, dance_kj_0_finished, dance_kj_0_reset),"));
        // Layer count is untouched.
        assert_eq!(layer_key_count(&out, 0).unwrap(), 9);
    }

    #[test]
    fn dance_extends_existing_oryx_infra() {
        // A source that already carries one Oryx dance.
        let src = format!(
            "enum tap_dance_codes {{
  DANCE_0,
}};
{SAMPLE}
uint8_t dance_step(tap_dance_state_t *state);
uint8_t dance_step(tap_dance_state_t *state) {{ return 1; }}
void dance_0_finished(tap_dance_state_t *state, void *user_data) {{}}
void dance_0_reset(tap_dance_state_t *state, void *user_data) {{}}
tap_dance_action_t tap_dance_actions[] = {{
        [DANCE_0] = ACTION_TAP_DANCE_FN_ADVANCED(NULL, dance_0_finished, dance_0_reset),
}};
"
        );
        let d = DanceSpec { layer: 1, position: 0, tap: Some("KC_TAB".into()), tap_hold: Some("MO(3)".into()), ..Default::default() };
        let out = apply_dances(&src, &[d]).unwrap();
        // Reuses the existing enum + step machinery (no duplicates).
        assert_eq!(out.matches("enum tap_dance_codes").count(), 1);
        assert_eq!(out.matches("uint8_t dance_step(tap_dance_state_t *state) {").count(), 1);
        assert_eq!(out.matches("tap_dance_actions[] = {").count(), 1);
        assert!(out.contains("DANCE_KJ_0,"));
        assert!(out.contains("case DOUBLE_HOLD: layer_on(3); break;"));
        // Both the old and the new registration live in the one array.
        let arr = &out[out.find("tap_dance_actions[] = {").unwrap()..];
        let arr = &arr[..arr.find("};").unwrap()];
        assert!(arr.contains("[DANCE_0]") && arr.contains("[DANCE_KJ_0]"));
        // Functions are defined before the array (C needs the symbols).
        assert!(out.find("dance_kj_0_finished(tap_dance_state_t *state, void *user_data) {").unwrap() < out.find("tap_dance_actions[] = {").unwrap());
    }

    #[test]
    fn dance_gets_comfortable_tapping_term() {
        // Existing get_tapping_term → our case injected before default.
        let src = "uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {\n    switch (keycode) {\n        default:\n            return TAPPING_TERM;\n    }\n}\n";
        let out = apply_dance_tapping_term(src, 2);
        assert!(out.contains("case TD(DANCE_KJ_0): return 200;"));
        assert!(out.contains("case TD(DANCE_KJ_1): return 200;"));
        assert_eq!(out.matches("get_tapping_term").count(), 1); // reused, not duplicated
        assert!(out.find("DANCE_KJ_0").unwrap() < out.find("default:").unwrap());
    }

    #[test]
    fn dance_tapping_term_creates_function_when_absent() {
        let out = apply_dance_tapping_term("// no get_tapping_term here\n", 1);
        assert!(out.contains("uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record)"));
        assert!(out.contains("case TD(DANCE_KJ_0): return 200;"));
        assert!(out.contains("default: return TAPPING_TERM;"));
    }

    #[test]
    fn full_dance_pipeline_sets_tapping_term() {
        // apply_dances end-to-end must land the tapping-term case.
        let src = format!(
            "enum tap_dance_codes {{\n  DANCE_0,\n}};\n{SAMPLE}\nuint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {{\n    switch (keycode) {{\n        default:\n            return TAPPING_TERM;\n    }}\n}}\nuint8_t dance_step(tap_dance_state_t *state);\nuint8_t dance_step(tap_dance_state_t *state) {{ return 1; }}\ntap_dance_action_t tap_dance_actions[] = {{\n}};\n"
        );
        let d = DanceSpec { layer: 0, position: 1, tap: None, hold: Some("MO(1)".into()), double_tap: None, tap_hold: Some("MO(2)".into()) };
        let out = apply_dances(&src, &[d]).unwrap();
        assert!(out.contains("case TD(DANCE_KJ_0): return 200;"));
        assert!(out.contains("case DOUBLE_HOLD: layer_on(2); break;"));
    }

    #[test]
    fn generated_dances_reject_nested_tap_hold_keycodes() {
        for code in ["TT(2)", "LT(2,KC_A)", "LGUI_T(KC_SPC)", "MT(MOD_LSFT,KC_A)"] {
            let dance = DanceSpec {
                layer: 0,
                position: 1,
                tap: Some(code.into()),
                ..Default::default()
            };
            let err = apply_dances(SAMPLE, &[dance]).unwrap_err().to_string();
            assert!(err.contains("cannot be nested inside a generated tap dance"));
        }
    }

    #[test]
    fn action_stmts_variants() {
        assert_eq!(action_stmts("MO(2)"), ("layer_on(2);".into(), "layer_off(2);".into()));
        assert_eq!(action_stmts("TO(1)"), ("layer_move(1);".into(), String::new()));
        assert_eq!(action_stmts("KC_A"), ("register_code16(KC_A);".into(), "unregister_code16(KC_A);".into()));
        // Layer families that used to fall through to register_code16:
        assert_eq!(action_stmts("LT(2,KC_A)"), ("layer_on(2);".into(), "layer_off(2);".into()));
        assert_eq!(
            action_stmts("OSL(2)"),
            (
                "if (is_oneshot_enabled()) { set_oneshot_layer(2, ONESHOT_START); } else { layer_on(2); }".into(),
                "if (is_oneshot_enabled()) { clear_oneshot_layer_state(ONESHOT_PRESSED); } else { layer_off(2); }".into(),
            )
        );
        assert_eq!(
            action_stmts("OSM(MOD_LSFT)"),
            (
                "if (is_oneshot_enabled()) { set_oneshot_mods(MOD_LSFT); } else { register_mods(MOD_LSFT); }".into(),
                "if (!is_oneshot_enabled()) { unregister_mods(MOD_LSFT); }".into(),
            )
        );
        assert_eq!(action_stmts("TT(3)"), ("layer_invert(3);".into(), String::new()));
        assert_eq!(action_stmts("DF(0)"), ("default_layer_set(1UL << 0);".into(), String::new()));
        assert_eq!(action_stmts("DF(3)"), ("default_layer_set(1UL << 3);".into(), String::new()));
        assert_eq!(
            action_stmts("KC_A\nTO(2)"),
            (
                "register_code16(KC_A); unregister_code16(KC_A); layer_move(2);".into(),
                String::new(),
            )
        );
    }

    #[test]
    fn add_layer_rejects_duplicate_and_out_of_range() {
        // SAMPLE has layers [0] and [1].
        assert!(add_layer(SAMPLE, 1, &[]).is_err(), "duplicate layer index must error");
        assert!(add_layer(SAMPLE, 2, &[(99, "KC_A".into())]).is_err(), "out-of-range key must error");
        assert!(add_layer(SAMPLE, 2, &[(1, "KC_A".into())]).is_ok());
    }

    #[test]
    fn missing_layer_errors() {
        let edits = [Edit { layer: 7, position: 0, keycode: "KC_A".into() }];
        assert!(apply_edits(SAMPLE, &edits).is_err());
    }
}
